development:
  adapter: postgresql
  encoding: unicode
  database: workapp24_development
  host: localhost
  pool: 5
  username: action
  password:
  
test:
  adapter: postgresql
  encoding: unicode
  database: workapp24_test
  host: localhost
  pool: 5
  username: action
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: workapp24_production
  host: localhost
  pool: 5
  username: action
  password: 